{
  config,
  lib,
  pkgs,
  ...
}:
let
  cfg = config.aurora;
  laptop = cfg.hardware.formFactor == "laptop";
  physical = cfg.hardware.formFactor != "vm";
  storage = cfg.storage;
  uuid =
    value:
    builtins.match "[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}" value
    != null;
  tools = pkgs.writeShellScriptBin "aurora-power" ''
    export PATH=${
      lib.makeBinPath [
        pkgs.python3
        pkgs.systemd
        pkgs.power-profiles-daemon
        pkgs.util-linux
        pkgs.coreutils
      ]
    }:$PATH
    exec python3 ${../../scripts/power.py} "$@"
  '';
in
{
  services.power-profiles-daemon.enable = lib.mkDefault physical;
  services.upower = {
    enable = lib.mkDefault physical;
    usePercentageForPolicy = true;
    percentageLow = 20;
    percentageCritical = 10;
    percentageAction = 5;
    # UPower falls back to PowerOff if logind cannot hibernate.
    criticalPowerAction = if cfg.power.hibernate then "Hibernate" else "PowerOff";
  };
  powerManagement.enable = lib.mkDefault physical;
  networking.networkmanager.wifi.powersave = lib.mkDefault (
    if cfg.power.wifiPowerSave != null then cfg.power.wifiPowerSave else laptop
  );
  zramSwap = {
    enable = true;
    priority = 100;
  };
  services.logind.settings.Login = lib.mkIf laptop {
    HandleLidSwitch = if cfg.power.hibernate then "suspend-then-hibernate" else "suspend";
    HandleLidSwitchExternalPower = "suspend";
    HandleLidSwitchDocked = "ignore";
  };
  systemd.sleep.settings.Sleep = {
    AllowHibernation = cfg.power.hibernate;
    AllowSuspendThenHibernate = cfg.power.hibernate;
    HibernateDelaySec = cfg.power.hibernateDelay;
    HibernateOnACPower = false;
  };
  boot.resumeDevice = lib.mkIf cfg.power.hibernate "/dev/disk/by-uuid/${storage.swapUuid}";
  boot.initrd.luks.devices.aurora = lib.mkIf (storage.layout == "encrypted") {
    device = "/dev/disk/by-uuid/${storage.luksUuid}";
  };
  boot.initrd.services.lvm.enable = lib.mkIf (storage.layout == "encrypted") true;
  # Generated hardware already declares active swap; don't duplicate that entry.
  swapDevices = lib.mkIf (storage.swapUuid != "") (
    lib.mkDefault [
      {
        device = "/dev/disk/by-uuid/${storage.swapUuid}";
        priority = 10;
      }
    ]
  );
  environment.systemPackages = [ tools ];
  systemd.services.aurora-charge-conservation =
    lib.mkIf (laptop && cfg.power.chargeConservation != "unchanged")
      {
        description = "Apply supported Lenovo charge conservation";
        wantedBy = [ "multi-user.target" ];
        after = [ "systemd-udev-settle.service" ];
        serviceConfig = {
          Type = "oneshot";
          ExecStart = "${tools}/bin/aurora-power conservation ${cfg.power.chargeConservation}";
        };
      };
  systemd.services.aurora-source-profile =
    lib.mkIf (laptop && (cfg.power.acProfile != "unchanged" || cfg.power.batteryProfile != "unchanged"))
      {
        description = "Apply power profile on supply transitions";
        wantedBy = [ "multi-user.target" ];
        after = [ "power-profiles-daemon.service" ];
        requires = [ "power-profiles-daemon.service" ];
        serviceConfig = {
          ExecStart = "${tools}/bin/aurora-power profiles ${cfg.power.acProfile} ${cfg.power.batteryProfile}";
          Restart = "on-failure";
          RestartSec = 5;
        };
      };
  assertions = [
    {
      assertion =
        !cfg.power.hibernate
        || (laptop && storage.layout == "encrypted" && uuid storage.swapUuid && storage.swapGiB > 0);
      message = "Hibernation requires a physical laptop and persistent encrypted swap UUID/size generated by setup.";
    }
    {
      assertion = storage.layout != "encrypted" || uuid storage.luksUuid;
      message = "Encrypted storage requires the target's generated LUKS UUID.";
    }
    {
      assertion = !(config.services.tlp.enable && config.services.power-profiles-daemon.enable);
      message = "Use one power profile manager; do not combine TLP and power-profiles-daemon.";
    }
  ];
}
